### ISSUE TITLE
[SecurityHub] InvalidAccessException when account is not subscribed

### ISSUE THREAD

**Issue by thejazzid** [joshlarsen/aws-recon#65]
Would it be possible to add feature, to proceed on some errors, for example if no services enabled, but still be able to collect other information? 
`/Users/user/.rvm/gems/ruby-2.6.5/gems/aws-sdk-core-3.109.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in 'call': Account 123123123123 is not subscribed to AWS Security Hub (Aws::SecurityHub::Errors::InvalidAccessException)`

**Comment by joshlarsen** [comment]
Hi @thejazzid, yes this is planned. This will likely have two components:

1. for errors that are related to service availability, silently ignore and continue. This is what we currently do, but it looks like we missed `EMR`.
2. for errors that are due to lack of permissions, ignore by default, with a command line option to raise the error.

**Comment by joshlarsen** [comment]
Also, @thejazzid, what region were you getting that `EMR` error from?

**Comment by thejazzid** [comment]
@joshlarsen Thanks for info. will be looking forward for new releases. I would love to contribute, but I'm not ruby guy. 

As for region - according to last successful commands it was ap-east-1

```
t7.ap-east-1.EC2.describe_vpc_peering_connections.0
t3.ap-east-1.RDS.describe_db_engine_versions.0
t3.ap-east-1.RDS.describe_db_engine_versions.1
t3.ap-east-1.RDS.describe_db_engine_versions.2
t3.ap-east-1.RDS.describe_db_engine_versions.3

Finished in 240 seconds. Saving resources to..... 

```

**Comment by joshlarsen** [comment]
Splitting this into two issues. The `EMR` issue is now #67.
